[package]
name = "q_denom"
version = "0.1"
lean_version = "leanprover-community/lean:3.32.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d869256e099ff9cf60dd1907814183ed822106b8"}
